//! TOML-file-driven configuration (`~/.ma/config.toml`).
//!
//! Mirrors the `ai-bridge` config convention (ADR-0005 there, ADR-0008 here):
//! one single file holds everything — the upstream format is declared
//! explicitly via `upstream_type` (never guessed from the URL), agent
//! behaviour is tuned through optional snake_case keys, unknown keys fail
//! startup (`deny_unknown_fields`), and a missing file drops a
//! fully-commented starter template next to the precise "missing field"
//! error instead of silently serving placeholder values. Only `$HOME` is
//! still read from the environment — to resolve the config path.

use crate::mcp::McpServerConfig;
use anyhow::{anyhow, Result};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Configuration lives in `~/.ma/<CONFIG_FILE_NAME>` (ADR-0008). The former
/// `MA_*` environment variables are gone; `$HOME` is the only environment
/// read, solely to resolve this path.
pub(crate) const CONFIG_DIR_NAME: &str = ".ma";
pub(crate) const CONFIG_FILE_NAME: &str = "config.toml";

const DEFAULT_MAX_TOKENS: usize = 128000;
const DEFAULT_MAX_TURNS: usize = 256;
const DEFAULT_MAX_TOOL_RESULT_BYTES: usize = 32 * 1024;
const DEFAULT_MCP_LIST_TOOLS_TIMEOUT_MS: u64 = 10_000;

/// Fully-commented starter template dropped as the requested config file when
/// it does not exist. Every value line is commented so the next launch fails
/// with a precise "missing field" error instead of silently running on
/// placeholder values.
///
/// Ordering matters (TOML rule): every top-level key comes BEFORE any table
/// header — after `[headers]`, bare keys would be parsed as members of that
/// table. The template therefore keeps all scalars up top and pins the three
/// tables to the bottom; a unit test uncomments the template and parses it so
/// this invariant cannot regress.
const DEFAULT_TEMPLATE: &str = r#"# ma config — this file is auto-generated by ma;
# fill in the required fields below and you're ready to start.
#
# Usage:
#   ma                 loads ~/.ma/config.toml (this file)
#   ma --config FILE   loads FILE instead
#
# Every line is commented out — uncomment and fill in real values before
# launching. Unknown keys are rejected at startup, so a typo can never
# silently disable a setting.
#
# TOML ordering: top-level keys MUST stay above the [tables] at the bottom —
# after a table header, bare keys become part of that table.

# ===================== Required =====================

# Upstream API format, one of: anthropic-messages | oai-chat
# It explicitly decides the auth header and wire format — no URL guessing.
#upstream_type = "oai-chat"

# Upstream API endpoint (matching the upstream_type)
#url = "https://api.example.com/v1"

# Upstream API key (OpenAI-family upstreams use Authorization: Bearer;
# Anthropic upstreams use x-api-key)
#api_key = "sk-your-upstream-key"

# ================= Optional top-level keys =================

# Model id. Default follows upstream_type: oai-chat -> deepseek-v4-flash,
# anthropic-messages -> claude-sonnet-4-5.
#model = "deepseek-v4-flash"

# Max output tokens per assistant turn. Default: 128000
#max_tokens = 128000

# Tool-loop iterations before giving up (exit 2). Default: 256
#max_turns = 256

# Turn budget for each `task` sub-agent. Default: inherits max_turns
#task_max_turns = 256

# Tools that must never run (refused before every execution path).
#deny_tools = ["bash"]

# Bash safety gate. Default: true; set false for pure-auto mode.
#gate = true

# Cap on tool output fed back into context. Default: 32768
#max_tool_result_bytes = 32768

# Per-server MCP connect + list_tools timeout in ms. Default: 10000
#mcp_list_tools_timeout_ms = 10000

# Directory for per-launch JSONL session logs (<yyyymmdd-HHmmss>.log).
# Unset = nothing is written.
#log_file_dir = ".ma-logs"

# Write threshold: debug | info | warn | error. Default: info
#log_level = "info"

# System prompt values — each may be a literal string OR a file path whose
# contents are inlined (point system_suffix at a CLAUDE.md to inject repo
# context).

# Prepended to the system prompt.
#system_prefix = ""

# Appended to the system prompt.
#system_suffix = ""

# Replaces the built-in persona entirely.
#persona = ""

# Replaces the whole prefix+persona+suffix composite.
#system_prompt = ""

# ================= Tables (keep these LAST) =================

# Extra request headers applied to every upstream request.
#[headers]
#X-Tenant = "default"

# Outbound reasoning parameter policy.
#[reasoning]
#thinking = true       # master switch, default true; when off, ALL reasoning params are stripped from outbound requests
#effort = "max"        # default max; off/drop/none/disable/disabled = drop the whole field;
#                      # any other value is trimmed, lowercased, and passed through as-is

# One [[mcp_servers]] table per server: stdio needs cmd (+ args/env),
# SSE needs url. A server that fails to connect is skipped, not fatal.
#[[mcp_servers]]
#name = "fs"
#cmd = "npx"
#args = ["-y", "@modelcontextprotocol/server-fs"]
#env = { KEY = "value" }

#[[mcp_servers]]
#name = "remote"
#url = "https://mcp.example.com/sse"
"#;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpstreamType {
    AnthropicMessages,
    OaiChat,
}

impl UpstreamType {
    fn parse(s: &str) -> Result<Self> {
        match s {
            "anthropic-messages" => Ok(UpstreamType::AnthropicMessages),
            "oai-chat" => Ok(UpstreamType::OaiChat),
            other => Err(anyhow!(
                "invalid upstream_type {other:?}: expected \"anthropic-messages\" or \"oai-chat\""
            )),
        }
    }

    fn default_model(self) -> &'static str {
        match self {
            UpstreamType::AnthropicMessages => "claude-sonnet-4-5",
            UpstreamType::OaiChat => "deepseek-v4-flash",
        }
    }
}

/// What to do with the outgoing reasoning-effort field (`reasoning_effort`
/// on Chat Completions): stamp this exact value (lowercased) or omit the
/// field entirely. Ported from the ai-bridge `[reasoning]` convention — the
/// configured value is the single source of truth, no per-model mapping is
/// applied on top of it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReasoningEffortOverride {
    Set(String),
    Drop,
}

/// Outbound reasoning policy resolved once at startup from the `[reasoning]`
/// config table:
/// - `thinking_enabled == false` (master switch off): all thinking affordances
///   are stripped from outgoing requests and `effort` is ignored;
/// - otherwise the effort override decides the outgoing effort value.
#[derive(Debug, Clone)]
pub struct ReasoningPolicy {
    /// Master switch from `[reasoning] thinking` (default on).
    pub thinking_enabled: bool,
    /// Effort policy from `[reasoning] effort` (default `max`).
    pub effort: ReasoningEffortOverride,
}

impl ReasoningPolicy {
    /// Resolve the policy from raw table values. Defaults: thinking on,
    /// effort `"max"`; the Drop keyword set mirrors ai-bridge exactly.
    fn parse(thinking: Option<bool>, effort: Option<&str>) -> Self {
        let thinking_enabled = thinking.unwrap_or(true);
        let effort = match effort.map(str::trim).filter(|v| !v.is_empty()) {
            None => ReasoningEffortOverride::Set("max".into()),
            Some(raw) => match raw.to_ascii_lowercase().as_str() {
                "off" | "drop" | "none" | "disable" | "disabled" => ReasoningEffortOverride::Drop,
                _ => ReasoningEffortOverride::Set(raw.to_ascii_lowercase()),
            },
        };
        Self {
            thinking_enabled,
            effort,
        }
    }

    /// The `reasoning_effort` value to emit for an `oai-chat` request under
    /// this policy, or `None` to omit the field entirely.
    pub fn audience_effort(&self) -> Option<&str> {
        if !self.thinking_enabled {
            return None;
        }
        match &self.effort {
            ReasoningEffortOverride::Set(v) => Some(v),
            ReasoningEffortOverride::Drop => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Config {
    pub upstream_type: UpstreamType,
    pub url: String,
    pub api_key: String,
    pub model: String,
    pub max_tokens: usize,
    pub reasoning: ReasoningPolicy,
    /// Extra headers applied to every upstream request, e.g. `Name: value`.
    pub extra_headers: Vec<(String, String)>,

    // Agent behaviour
    pub max_turns: usize,
    /// Turn budget for a `task` sub-agent; `None` inherits `max_turns`.
    pub task_max_turns: Option<usize>,
    /// Names of tools that must not be invoked (e.g. `["bash"]`).
    pub deny_tools: Vec<String>,
    /// Whether the LLM safety gate guards `bash` execution. `gate = false` disables.
    pub gate_enabled: bool,
    /// Byte threshold for tool results: results at or below this size pass
    /// through to the model unchanged; larger ones are compressed by a separate
    /// LLM call (`max_tool_result_bytes`).
    pub max_tool_result_bytes: usize,

    // MCP
    pub mcp_servers: Vec<McpServerConfig>,
    pub mcp_list_tools_timeout_ms: u64,

    // System prompt
    pub system_prefix: Option<String>,
    pub system_suffix: Option<String>,
    pub persona: Option<String>,
    /// When set, REPLACES the whole prefix+persona+suffix composite
    /// (`system_prompt`; string or file path).
    pub system_prompt: Option<String>,

    // Logging
    pub log_dir: Option<PathBuf>,
    pub log_level: String,
}

/// Resolve the default config path: `$HOME/.ma/config.toml` (ADR-0008).
pub fn default_path() -> Result<PathBuf> {
    config_path(std::env::var("HOME").ok().as_deref())
}

/// Injected variant of [`default_path`] so tests never mutate `$HOME`.
fn config_path(home: Option<&str>) -> Result<PathBuf> {
    match home.map(str::trim).filter(|h| !h.is_empty()) {
        Some(home) => Ok(Path::new(home).join(CONFIG_DIR_NAME).join(CONFIG_FILE_NAME)),
        None => Err(anyhow!(
            "HOME environment variable is not set; cannot resolve ~/.ma/{CONFIG_FILE_NAME}"
        )),
    }
}

/// Load and parse the config file at `path`. A missing file surfaces an error
/// that — best effort — drops the commented starter template at the same path
/// so first-time users have something concrete to edit.
pub fn load(path: &Path) -> Result<Config> {
    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(missing_config_error(path));
        }
        Err(e) => return Err(anyhow!("failed to read config {}: {e}", path.display())),
    };

    let raw: RawConfig = toml::from_str(&text).map_err(|e| {
        anyhow!("invalid config {}: {e}", path.display())
    })?;
    build_config(raw)
}

/// Build the not-found error, attempting to leave a starter template behind
/// so first-time users have something concrete to edit. Template failures are
/// warned about on stderr (the session logger is not up yet), never masking
/// the original error.
fn missing_config_error(path: &Path) -> anyhow::Error {
    let mut msg = format!("config not found: {}", path.display());
    match write_starter_template(path) {
        Ok(true) => msg.push_str(
            "; a starter template was written to that path — \
             fill in the required keys and rerun",
        ),
        Ok(false) => {}
        Err(e) => eprintln!("warning: could not write starter template: {e}"),
    }
    anyhow!(msg)
}

/// Ensure the parent directory exists and drop the commented starter template
/// at `path`. Returns whether a new file was written; never overwrites.
fn write_starter_template(path: &Path) -> std::io::Result<bool> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    if path.exists() {
        return Ok(false);
    }
    std::fs::write(path, DEFAULT_TEMPLATE)?;
    Ok(true)
}

// ---------------------------------------------------------------------------
// Raw serde layer → runtime Config conversion
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawConfig {
    upstream_type: String,
    url: String,
    api_key: String,
    #[serde(default)]
    model: Option<String>,
    #[serde(default)]
    max_tokens: Option<usize>,
    #[serde(default)]
    headers: BTreeMap<String, String>,
    #[serde(default)]
    reasoning: Option<RawReasoning>,
    #[serde(default)]
    max_turns: Option<usize>,
    #[serde(default)]
    task_max_turns: Option<usize>,
    #[serde(default)]
    deny_tools: Vec<String>,
    #[serde(default)]
    gate: Option<bool>,
    #[serde(default)]
    max_tool_result_bytes: Option<usize>,
    #[serde(default)]
    mcp_servers: Vec<McpServerConfig>,
    #[serde(default)]
    mcp_list_tools_timeout_ms: Option<u64>,
    #[serde(default)]
    log_file_dir: Option<String>,
    #[serde(default)]
    log_level: Option<String>,
    #[serde(default)]
    system_prefix: Option<String>,
    #[serde(default)]
    system_suffix: Option<String>,
    #[serde(default)]
    persona: Option<String>,
    #[serde(default)]
    system_prompt: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawReasoning {
    #[serde(default)]
    thinking: Option<bool>,
    #[serde(default)]
    effort: Option<String>,
}

fn build_config(raw: RawConfig) -> Result<Config> {
    let upstream_type = UpstreamType::parse(&raw.upstream_type)?;

    let reasoning = match &raw.reasoning {
        Some(r) => ReasoningPolicy::parse(r.thinking, r.effort.as_deref()),
        None => ReasoningPolicy::parse(None, None),
    };

    Ok(Config {
        upstream_type,
        url: raw.url,
        api_key: raw.api_key,
        model: raw.model.unwrap_or_else(|| upstream_type.default_model().into()),
        max_tokens: raw.max_tokens.unwrap_or(DEFAULT_MAX_TOKENS),
        reasoning,
        extra_headers: raw.headers.into_iter().collect(),
        max_turns: raw.max_turns.unwrap_or(DEFAULT_MAX_TURNS),
        task_max_turns: raw.task_max_turns,
        deny_tools: raw.deny_tools,
        gate_enabled: raw.gate.unwrap_or(true),
        max_tool_result_bytes: raw.max_tool_result_bytes.unwrap_or(DEFAULT_MAX_TOOL_RESULT_BYTES),
        mcp_servers: raw.mcp_servers,
        mcp_list_tools_timeout_ms: raw
            .mcp_list_tools_timeout_ms
            .unwrap_or(DEFAULT_MCP_LIST_TOOLS_TIMEOUT_MS),
        system_prefix: raw.system_prefix,
        system_suffix: raw.system_suffix,
        persona: raw.persona,
        system_prompt: raw.system_prompt,
        log_dir: raw.log_file_dir.map(PathBuf::from),
        log_level: raw.log_level.unwrap_or_else(|| "info".into()),
    })
}

#[cfg(test)]
mod tests {
    use super::{
        build_config, config_path, load, write_starter_template, RawConfig,
        ReasoningEffortOverride, CONFIG_DIR_NAME, CONFIG_FILE_NAME, DEFAULT_TEMPLATE,
    };
    use std::fs;
    use std::path::Path;

    const MINIMAL_TOML: &str = r#"
upstream_type = "oai-chat"
url = "https://api.example.com/v1"
api_key = "sk-test"
"#;

    fn write_cfg(dir: &Path, content: &str) -> std::path::PathBuf {
        let path = dir.join(CONFIG_FILE_NAME);
        fs::write(&path, content).expect("write config");
        path
    }

    fn load_minimal(dir: &Path) -> crate::config::Config {
        load(&dir.join(CONFIG_FILE_NAME)).expect("minimal config loads")
    }

    // -----------------------------------------------------------------------
    // Parsing & defaults
    // -----------------------------------------------------------------------

    #[test]
    fn minimal_toml_uses_defaults() {
        let dir = tempfile::tempdir().unwrap();
        write_cfg(dir.path(), MINIMAL_TOML);
        let cfg = load_minimal(dir.path());

        assert_eq!(cfg.upstream_type, crate::config::UpstreamType::OaiChat);
        assert_eq!(cfg.url, "https://api.example.com/v1");
        assert_eq!(cfg.api_key, "sk-test");
        assert_eq!(cfg.model, "deepseek-v4-flash");
        assert_eq!(cfg.max_tokens, 128000);
        assert_eq!(cfg.extra_headers.len(), 0);
        assert_eq!(cfg.max_turns, 256);
        assert_eq!(cfg.task_max_turns, None);
        assert!(cfg.deny_tools.is_empty());
        assert!(cfg.gate_enabled);
        assert_eq!(cfg.max_tool_result_bytes, 32 * 1024);
        assert!(cfg.mcp_servers.is_empty());
        assert_eq!(cfg.mcp_list_tools_timeout_ms, 10_000);
        assert_eq!(cfg.system_prefix, None);
        assert_eq!(cfg.system_suffix, None);
        assert_eq!(cfg.persona, None);
        assert_eq!(cfg.system_prompt, None);
        assert_eq!(cfg.log_dir, None);
        assert_eq!(cfg.log_level, "info");
        // Reasoning defaults mirror ai-bridge: thinking on, effort max.
        assert!(cfg.reasoning.thinking_enabled);
        assert_eq!(
            cfg.reasoning.effort,
            ReasoningEffortOverride::Set("max".into())
        );
    }

    #[test]
    fn full_toml_maps_every_field() {
        // Top-level keys must precede any table header (TOML rule), so the
        // [[mcp_servers]] array comes last.
        let toml = r#"
upstream_type = "anthropic-messages"
url = "https://a.example/v1"
api_key = "ak"
model = "m1"
max_tokens = 8192
max_turns = 5
task_max_turns = 3
deny_tools = ["bash", "web_fetch"]
gate = false
max_tool_result_bytes = 1024
mcp_list_tools_timeout_ms = 500
log_file_dir = "/tmp/ma-logs"
log_level = "debug"
system_prefix = "pre"
system_suffix = "/path/to/CLAUDE.md"
persona = "p"
system_prompt = "sp"

[headers]
X-Tenant = "t1"
X-Trace = "7"

[reasoning]
thinking = false
effort = "LOW"

[[mcp_servers]]
name = "fs"
cmd = "npx"
args = ["-y", "@modelcontextprotocol/server-fs"]
env = { KEY = "value" }

[[mcp_servers]]
name = "remote"
url = "https://mcp.example.com/sse"
"#;
        let dir = tempfile::tempdir().unwrap();
        write_cfg(dir.path(), toml);
        let cfg = load_minimal(dir.path());

        assert_eq!(cfg.upstream_type, crate::config::UpstreamType::AnthropicMessages);
        assert_eq!(cfg.model, "m1");
        assert_eq!(cfg.max_tokens, 8192);
        assert_eq!(
            cfg.extra_headers,
            vec![
                ("X-Tenant".to_string(), "t1".to_string()),
                ("X-Trace".to_string(), "7".to_string()),
            ]
        );

        // Master switch off wins over whatever effort says.
        assert!(!cfg.reasoning.thinking_enabled);
        assert_eq!(
            cfg.reasoning.effort,
            ReasoningEffortOverride::Set("low".into())
        );
        assert_eq!(cfg.reasoning.audience_effort(), None);

        assert_eq!(cfg.max_turns, 5);
        assert_eq!(cfg.task_max_turns, Some(3));
        assert_eq!(cfg.deny_tools, vec!["bash", "web_fetch"]);
        assert!(!cfg.gate_enabled);
        assert_eq!(cfg.max_tool_result_bytes, 1024);

        assert_eq!(cfg.mcp_servers.len(), 2);
        assert_eq!(cfg.mcp_servers[0].name, "fs");
        assert_eq!(cfg.mcp_servers[0].cmd.as_deref(), Some("npx"));
        assert_eq!(cfg.mcp_servers[0].args, vec!["-y", "@modelcontextprotocol/server-fs"]);
        assert_eq!(cfg.mcp_servers[0].env.get("KEY").map(String::as_str), Some("value"));
        assert_eq!(cfg.mcp_servers[1].url.as_deref(), Some("https://mcp.example.com/sse"));
        assert_eq!(cfg.mcp_list_tools_timeout_ms, 500);

        assert_eq!(cfg.log_dir, Some("/tmp/ma-logs".into()));
        assert_eq!(cfg.log_level, "debug");
        assert_eq!(cfg.system_prefix.as_deref(), Some("pre"));
        assert_eq!(cfg.system_suffix.as_deref(), Some("/path/to/CLAUDE.md"));
        assert_eq!(cfg.persona.as_deref(), Some("p"));
        assert_eq!(cfg.system_prompt.as_deref(), Some("sp"));
    }

    // -----------------------------------------------------------------------
    // Reasoning table
    // -----------------------------------------------------------------------

    fn reasoning_of(toml: &str) -> crate::config::ReasoningPolicy {
        let dir = tempfile::tempdir().unwrap();
        write_cfg(dir.path(), &format!("{MINIMAL_TOML}\n{toml}"));
        load_minimal(dir.path()).reasoning
    }

    #[test]
    fn reasoning_drop_keywords() {
        for kw in ["off", "drop", "none", "disable", "disabled", " OFF ", "Disabled"] {
            let policy = reasoning_of(&format!("[reasoning]\neffort = \"{kw}\"\n"));
            assert_eq!(
                policy.effort,
                ReasoningEffortOverride::Drop,
                "keyword {kw:?} should drop"
            );
            assert_eq!(policy.audience_effort(), None);
        }
    }

    #[test]
    fn reasoning_custom_values_pass_through_lowercased() {
        let policy = reasoning_of("[reasoning]\neffort = \" XHigh \"\n");
        assert!(policy.thinking_enabled);
        assert_eq!(
            policy.effort,
            ReasoningEffortOverride::Set("xhigh".into())
        );
        assert_eq!(policy.audience_effort(), Some("xhigh"));
    }

    #[test]
    fn reasoning_thinking_off_ignores_effort() {
        let policy = reasoning_of("[reasoning]\nthinking = false\neffort = \"high\"\n");
        assert!(!policy.thinking_enabled);
        assert_eq!(policy.audience_effort(), None);
    }

    #[test]
    fn reasoning_blank_effort_falls_back_to_default_max() {
        let policy = reasoning_of("[reasoning]\neffort = \"   \"\n");
        assert_eq!(
            policy.effort,
            ReasoningEffortOverride::Set("max".into())
        );
    }

    // -----------------------------------------------------------------------
    // Rejections
    // -----------------------------------------------------------------------

    fn load_err(content: &str) -> String {
        let dir = tempfile::tempdir().unwrap();
        let path = write_cfg(dir.path(), content);
        load(&path).expect_err("should fail").to_string()
    }

    #[test]
    fn unknown_key_is_rejected_with_name_and_path() {
        let err = load_err(&format!("{MINIMAL_TOML}\nbogus_key = 1\n"));
        assert!(err.contains("bogus_key"), "err: {err}");
        assert!(err.contains(CONFIG_FILE_NAME), "err: {err}");
    }

    #[test]
    fn wrong_type_is_rejected() {
        let err = load_err(&format!("{MINIMAL_TOML}\nmax_turns = \"x\"\n"));
        assert!(err.contains("max_turns"), "err: {err}");
    }

    #[test]
    fn out_of_range_value_is_rejected() {
        // usize rejects negative numbers outright.
        let err = load_err(&format!("{MINIMAL_TOML}\nmax_tokens = -1\n"));
        assert!(err.contains("max_tokens"), "err: {err}");
    }

    #[test]
    fn missing_required_field_is_named() {
        let err = load_err("upstream_type = \"oai-chat\"\nurl = \"https://x\"\n");
        assert!(err.contains("missing field") && err.contains("api_key"), "err: {err}");
    }

    #[test]
    fn malformed_toml_is_rejected_with_path() {
        let err = load_err("not [ valid");
        assert!(err.contains("invalid config"), "err: {err}");
    }

    #[test]
    fn invalid_upstream_type_is_rejected() {
        let err = load_err(
            "upstream_type = \"bogus\"\nurl = \"https://x\"\napi_key = \"k\"\n",
        );
        assert!(err.contains("upstream_type"), "err: {err}");
    }

    #[test]
    fn unknown_reasoning_key_is_rejected() {
        let err = load_err(&format!("{MINIMAL_TOML}\n[reasoning]\nbogus = 1\n"));
        assert!(err.contains("bogus"), "err: {err}");
    }

    // -----------------------------------------------------------------------
    // Paths & starter template
    // -----------------------------------------------------------------------

    #[test]
    fn config_path_resolves_home_or_errors() {
        assert_eq!(
            config_path(Some("/Users/x")).unwrap(),
            Path::new("/Users/x").join(CONFIG_DIR_NAME).join(CONFIG_FILE_NAME)
        );
        assert!(config_path(None).is_err());
        assert!(config_path(Some("")).is_err());
        assert!(config_path(Some("   ")).is_err());
    }

    #[test]
    fn missing_config_reports_path_and_writes_template() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(CONFIG_FILE_NAME);
        let err = load(&path).expect_err("should fail");
        let msg = err.to_string();
        assert!(msg.contains(&path.display().to_string()), "msg: {msg}");
        assert!(msg.contains("starter template"), "msg: {msg}");
        assert!(path.is_file(), "starter template should exist");

        // The template itself parses but names every required field.
        let again = load(&path).expect_err("commented template should still fail");
        assert!(
            again.to_string().contains("missing field"),
            "again: {again}"
        );
    }

    #[test]
    fn existing_template_is_never_overwritten() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(CONFIG_FILE_NAME);
        fs::write(&path, "sentinel\n").unwrap();

        let err = load(&path).expect_err("should fail");
        assert!(
            !err.to_string().contains("starter template"),
            "existing file must not be reported as written: {err}"
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), "sentinel\n");
    }

    #[test]
    fn write_template_creates_missing_directory() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("deep/new/dir").join(CONFIG_FILE_NAME);
        assert!(write_starter_template(&nested).unwrap());
        assert!(nested.is_file());
        // Second call over an existing file writes nothing.
        assert!(!write_starter_template(&nested).unwrap());
    }

    /// Uncomment the template's key/value and table-header lines (first
    /// non-`#` content is a snake_case identifier followed by `=`, or a `[`),
    /// leaving prose lines commented — simulating a user who enabled every
    /// setting at once.
    fn uncomment_template(template: &str) -> String {
        template
            .lines()
            .map(|line| {
                let Some(body) = line.strip_prefix('#') else {
                    return line;
                };
                let t = body.trim_start();
                let ident: usize = t
                    .chars()
                    .take_while(|c| c.is_ascii_lowercase() || *c == '_' || c.is_ascii_digit())
                    .count();
                let starts_kv = ident > 0 && t[ident..].trim_start().starts_with('=');
                if t.starts_with('[') || starts_kv {
                    body
                } else {
                    line
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    #[test]
    fn uncommented_template_parses_and_top_level_keys_precede_tables() {
        // TOML rule: after a table header, bare keys belong to that table. If
        // a top-level key ever drifts below one in DEFAULT_TEMPLATE, this
        // parse fails on unknown fields (or silently swallows keys into
        // [[mcp_servers]] entries, caught by the spot checks below).
        let enabled = uncomment_template(DEFAULT_TEMPLATE);
        let cfg = build_config(toml::from_str::<RawConfig>(&enabled).expect(
            "fully-uncommented template must parse; \
             suspect a top-level key below a [table] header",
        ))
        .expect("uncommented template should build");

        assert_eq!(cfg.model, "deepseek-v4-flash");
        assert_eq!(cfg.max_tokens, 4096);
        assert_eq!(cfg.max_turns, 20);
        // Would be None/absent if these keys were swallowed by a table above.
        assert_eq!(cfg.log_dir, Some("ma-logs".into()));
        assert_eq!(cfg.system_prefix, Some(String::new()));
        assert_eq!(cfg.mcp_list_tools_timeout_ms, 10_000);
        // The tables themselves still landed where they belong.
        assert!(cfg.reasoning.thinking_enabled);
        assert_eq!(
            cfg.reasoning.effort,
            ReasoningEffortOverride::Set("max".into())
        );
        assert_eq!(cfg.mcp_servers.len(), 2);
    }

    #[test]
    fn build_config_rejects_bad_upstream_type() {
        let parsed: super::RawConfig =
            toml::from_str("upstream_type = \"x\"\nurl = \"u\"\napi_key = \"k\"\n").unwrap();
        assert!(build_config(parsed).is_err());
    }
}
